### ISSUE TITLE
No Maintenance Intended Label is still present

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/scikit-aero#23]
In #22 it was agreed to remove `No Maintenance Intended` label but I can still see it after merge. Do you finally want to remove it.

**Comment by Juanlu001** [comment]
Oops, I overlooked this. @ashwinvis I'm assigning this one to you, in case you want to at least make a release with the latest changes :)

**Comment by jorgepiloto** [comment]
I am planning to use `skaero` for my aerospace degree tasks and homework. Therefore, I would like to know if maintenance is desired in order to solve some of the established issues and add new functionalities :+1:

**Comment by Juanlu001** [comment]
We agreed to remove the `No Maintenance Intended` because I understood @ashwinvis wanted to maintain the package. Maintaining means: be willing to merge pull requests, making a release from time to time, and in general take care of the package. @jorgepiloto if you want to be such a person I will gladly give you write permissions and you can do whatever you want :) If you feel overwhelmed, you can use your fork.

Unfortunately, and even though people keep using this package, I can't maintain it anymore. However, if someone else steps up and is willing to maintain, I can contribute things like an updated continuous integration, check that everything works in Python 3.7 and stuff like that.

**Comment by jorgepiloto** [comment]
It will be a pleasure to maintain it! Furthermore, will help me not only with my studies but also improving my Python skills :relaxed:

**Comment by Juanlu001** [comment]
Done :tada: 

Please, consider using pull requests instead of pushing to master. In any case, nobody will stop you :wink: 

Don't forget to close this issue if you finally remove the banner.

**Comment by jorgepiloto** [comment]
Closing this after #25 guys, hope to add more functionalities in the following days :rocket:

**Comment by Juanlu001** [comment]
Awesome!!!
